### ISSUE TITLE
What is args.unit in main_TUs_kernels.py?

### ISSUE THREAD

**Issue by williamweiwu** [se-ok/WLsimilarity#2]
Hi,

I have run the program, but there is a new issue in main_TUs_kernels.py.

In Line 184, _normalizer = 'unit' if args.unit else 'normal'. However, in def get_args() from Line 27 to 37, no 'unit' is provided.

How should I do it?

Thanks
Wei

**Comment by se-ok** [comment]
Hi Wei,

I am sorry for the poor code. It is an artifact while simplifying experimental code to post.
As you can see further down the code, line 184 is purely for logging, and you can replace it with
`_normalizer = 'normal'`.

I checked the code running properly with script `sh script_main_TUs_kernels.sh 0 BZR`.
I updated the repo too.

Thank you for reporting the issue, and let me know if there are further issues.
Seongmin

**Comment by williamweiwu** [comment]
> Hi Wei,
> 
> I am sorry for the poor code. It is an artifact while simplifying experimental code to post.
> As you can see further down the code, line 184 is purely for logging, and you can replace it with
> `_normalizer = 'normal'`.
> 
> I checked the code running properly with script `sh script_main_TUs_kernels.sh 0 BZR`.
> I updated the repo too.
> 
> Thank you for reporting the issue, and let me know if there are further issues.
> Seongmin

thx!
